@startuml
title Generate Account Report - GET /accounts/:account_id/report

actor Requester
boundary AccountGetReportHandler <<accountHandler.go>>
control AccountService <<serviceAccount.go>>
entity AccountFirestore <<model/account/firestore.go>>
entity TransferFirestore <<model/transfer/firestore.go>>
entity DepositFirestore <<model/deposit/firestore.go>>
entity WithdrawalFirestore <<model/withdrawal/firestore.go>>
entity AutoDebitFirestore <<model/automaticDebit/firestore.go>>

Requester -> AccountGetReportHandler : 1. GET /accounts/report/:account_id
activate AccountGetReportHandler

alt Authorization Failed
    AccountGetReportHandler -->> Requester : 2.HTTP Error Response
else Authorization Succeeded
    AccountGetReportHandler -> AccountService : 2. Report(accountID_from_path)
    activate AccountService
    
    AccountService -> AccountService : 3. Get(accountID)
    activate AccountService
    AccountService -> AccountFirestore : 4. Get(&accountID)
    activate AccountFirestore
    AccountFirestore -->> AccountService : 5. accountInfo / Error
    deactivate AccountFirestore
    deactivate AccountService
    
    alt Get AccountInfo Failed
        AccountService -->> AccountGetReportHandler : 6. Error
        AccountGetReportHandler -->> Requester : 7. HTTP Error Response
    else Get AccountInfo Succeeded
        
        AccountService -> TransferFirestore : 6. GetFiltered(account_id==accountID)
        activate TransferFirestore
        TransferFirestore -->> AccountService : 7. filteredTransfer / Error
        deactivate TransferFirestore
        note right of TransferFirestore : Filters transfers by accountID
        
        AccountService -> DepositFirestore : 8. GetFiltered(account_id==accountID)
        activate DepositFirestore
        DepositFirestore -->> AccountService : 9. filteredDeposits / Error
        deactivate DepositFirestore
        note right of DepositFirestore : Filters deposits by accountID
        
        AccountService -> WithdrawalFirestore : 10. GetFiltered(account_id==accountID)
        activate WithdrawalFirestore
        WithdrawalFirestore -->> AccountService : 11. filteredWithdrawals / Error
        deactivate WithdrawalFirestore
        note right of WithdrawalFirestore : Filters withdrawals by accountID


        AccountService -> AutoDebitFirestore : 12. GetFiltered(account_id==accountID)
        activate AutoDebitFirestore
        AutoDebitFirestore -->> AccountService : 13. filteredAutodebits / Error
        deactivate AutoDebitFirestore
        note right of AutoDebitFirestore : Filters autoDebits by accountID


        note right of AccountService : Assembles AccountReport from all data
        AccountService -->>  AccountGetReportHandler : 14. accountReport
        AccountGetReportHandler -->> Requester : 15. HTTP 200 OK (accountReport)
        
    end
    deactivate AccountService
end
deactivate AccountGetReportHandler
@enduml