@startuml
title Client UnBlock - PUT /clients/:client_id

actor Requester
boundary ClientPutHandler <<clientHandler.go>>
control ClientService <<serviceService.go>>
entity ClientFirestore <<model/client/firestore.go>>

activate Requester
Requester -> ClientPutHandler : 1. PUT /clients/:client_id

activate ClientPutHandler

alt Authorization Failed
    ClientPutHandler --> Requester : 2. HTTP Error Response
else Authorization Succeeded
    ClientPutHandler -> ClientService : 2. Update(clientID)
    activate ClientService
    ClientService -> ClientService : 3. Client(clientID)
    ClientService -> ClientFirestore : 4. Get(&clientID)
    activate ClientFirestore
    ClientFirestore --> ClientService : 5. ClientData / Error
    deactivate ClientFirestore
    alt Get Client Failed
        ClientService --> ClientService : 6. Error
        ClientService --> ClientPutHandler : 7. Error
        ClientPutHandler --> Requester : 8. HTTP Error Response
    else Get Client Succeeded
        ClientService --> ClientService : 6. Client
        ClientService -> ClientFirestore : 7. Update(Client with Status="active")
        activate ClientFirestore
        ClientFirestore --> ClientService : 8. nil / Error
        deactivate ClientFirestore
        alt Update Client Failed
            ClientService --> ClientPutHandler : 9. Error
            ClientPutHandler --> Requester : 10. HTTP Error Response
        else Update Client Succeeded
            ClientService --> ClientPutHandler : 9. nil
            ClientPutHandler --> Requester : 10. HTTP 200 OK (Client Blocked)
        end
        deactivate ClientService
    end
    deactivate ClientPutHandler
end
deactivate Requester

@enduml