@startuml
title Delete Account - DELETE /accounts/:account_id

actor Requester
boundary AccountDeleteHandler <<accountHandler.go>>
control AuthorizeService <<serviceAuthorize.go>>
control AccountService <<serviceAccount.go>>
entity AccountFirestore <<model/account/firestore.go>>

activate Requester

Requester -> AccountDeleteHandler : 1. DELETE /accounts/:account_id

activate AccountDeleteHandler

alt Authorization Failed
    AccountDeleteHandler -->> Requester : 2. HTTP Error Response
else Authorization Succeeded

    AccountDeleteHandler -> AccountService : 2. AccountDelete(accountID_from_path)
    activate AccountService
    AccountService -> AccountFirestore : 3. Delete(&accountID_from_path)
    activate AccountFirestore
    AccountFirestore -->> AccountService : 4. nil / Error
    deactivate AccountFirestore
    
    alt Delete Account Failed
        AccountService -->> AccountDeleteHandler : 5. Error
        AccountDeleteHandler -->> Requester : 6. HTTP Error Response
    else Delete Account Succeeded
        AccountService -->> AccountDeleteHandler : 5. nil
        AccountDeleteHandler -->> Requester : 6. bHTTP 200 OK (Message: Account Deleted)
    end
    deactivate AccountService
end
deactivate AccountDeleteHandler

deactivate Requester
@enduml