@startuml
title Get Account - GET /accounts/:account_id

actor Requester
boundary AccountGetHandler <<accountHandler.go>>
control AccountService <<serviceAccount.go>>
entity AccountFirestore <<model/account/firestore.go>>

Requester -> AccountGetHandler : 1. GET /accounts/:account_id
activate AccountGetHandler

alt Authorization Failed
    AccountGetHandler -->> Requester : 2. HTTP Error Response
else Authorization Succeeded
    AccountGetHandler -> AccountService : 2. Account(accountID_from_path)
    activate AccountService
    AccountService -> AccountFirestore : 3. Get(&accountID_from_path)
    activate AccountFirestore
    AccountFirestore -->> AccountService : 4. accountData / Error
    deactivate AccountFirestore
    
    alt Get Account Failed
        AccountService -->> AccountGetHandler : 5. Error
        AccountGetHandler -->> Requester : 6. HTTP Error Response
    else Get Account Succeeded
        AccountService -->> AccountGetHandler : 5. accountResponse
        AccountGetHandler -->> Requester : 6. HTTP 200 OK (accountResponse)
    end
    deactivate AccountService
end
deactivate AccountGetHandler
@enduml