@startuml
title Get Client - GET /clients/:client_id

actor Requester
boundary ClientGetHandler <<clientHandler.go>>
control ClientService <<serviceClient.go>>
entity ClientFirestore <<model/client/firestore.go>>

Requester -> ClientGetHandler : 1. GET /clients/:client_id
activate ClientGetHandler


alt Authorization Failed
    ClientGetHandler -->> Requester : 2. HTTP Error Response
else Authorization Succeeded
    ClientGetHandler -> ClientService : 2. Client(clientID_from_path)
    activate ClientService
    ClientService -> ClientFirestore : 3. Get(&clientID_from_path)
    activate ClientFirestore
    ClientFirestore -->> ClientService : 4. clientData / Error
    deactivate ClientFirestore
    
    alt Get Client Failed
        ClientService -->> ClientGetHandler : 5. Error
        ClientGetHandler -->> Requester : 6. HTTP Error Response
    else Get Client Succeeded
        ClientService -->> ClientGetHandler : 5. clientResponse
        ClientGetHandler -->> Requester : 6. HTTP 200 OK (clientResponse)
    end
    deactivate ClientService
end
deactivate ClientGetHandler
@enduml