@startuml
title Delete User - DELETE /users/:user_id

actor Requester
boundary UserDeleteHandler <<userHandler.go>>
control AuthorizeService <<serviceAuthorize.go>>
control UserService <<serviceDeleteTypes.go>>
entity UserFirestore <<model/user/firestore.go>>

activate Requester 

Requester -> UserDeleteHandler : 1. DELETE /users/:user_id
activate UserDeleteHandler

alt Authorization Failed (or user_id mismatch with claims.Id)
    UserDeleteHandler -->> Requester : 2. HTTP Error Response
else Authorization Succeeded
   
    UserDeleteHandler -> UserService : 2. UserDelete(userIDFromClaims_or_path)
    activate UserService
    UserService -> UserFirestore : 3. Delete(&userIDFromClaims_or_path)
    activate UserFirestore
    UserFirestore -->> UserService : 4. nil / Error
    deactivate UserFirestore
    
    alt Delete User Failed
        UserService -->> UserDeleteHandler : 5. Error
        UserDeleteHandler -->> Requester : 6. HTTP Error Response
    else Delete User Succeeded
        UserService -->> UserDeleteHandler : 5. nil
        UserDeleteHandler -->> Requester : 6. HTTP 200 OK (Message: User deleted)
    end
    deactivate UserService
end
deactivate UserDeleteHandler

deactivate Requester
@enduml