@startuml
title Delete Client - DELETE /clients/:client_id

actor Requester
boundary ClientDeleteHandler <<clientHandler.go>>
control AuthorizeService <<serviceAuthorize.go>>
control ClientService <<serviceDeleteTypes.go>>
entity ClientFirestore <<model/client/firestore.go>>

activate Requester 

Requester -> ClientDeleteHandler : 1. DELETE /clients/:client_id
activate ClientDeleteHandler

alt Authorization Failed
    ClientDeleteHandler -->> Requester : 2. HTTP Error Response
else Authorization Succeeded

    ClientDeleteHandler -> ClientService : 2. ClientDelete(clientID_from_path)
    activate ClientService
    ClientService -> ClientFirestore : 3. (&clientID_from_path)
    activate ClientFirestore
    ClientFirestore -->> ClientService : 4. nil / Error
    deactivate ClientFirestore
    
    alt Delete Client Failed
        ClientService -->> ClientDeleteHandler : 5. Error
        ClientDeleteHandler -->> Requester : 6. HTTP Error Response
    else Delete Client Succeeded
        ClientService -->> ClientDeleteHandler : 5. nil
        ClientDeleteHandler -->> Requester : 6. HTTP 200 OK (Message: Client deleted seccesfully)
    end
    deactivate ClientService
end
deactivate ClientDeleteHandler

deactivate Requester
@enduml