@startuml
title Account Block - PUT /accounts/:account_id

actor Requester
boundary AccountPutHandler <<accountHandler.go>>
control AccountService <<serviceAccount.go>>
entity AccountFirestore <<model/account/firestore.go>>

activate Requester
Requester -> AccountPutHandler : 1. PUT /accounts/:account_id
activate AccountPutHandler

alt Authorization Failed
    AccountPutHandler --> Requester : 2. HTTP Error Response
else Authorization Succeeded
    AccountPutHandler -> AccountService : 3. Update(accountID)
    activate AccountService
    AccountService -> AccountService : 4. Account(accountID)
    AccountService -> AccountFirestore : 5. Get(&accountID)
    activate AccountFirestore
    AccountFirestore --> AccountService : 6. accountData / Error
    deactivate AccountFirestore
    alt Get Account Failed
        AccountService --> AccountService : 7. Error
        AccountService --> AccountPutHandler : 8. Error
        AccountPutHandler --> Requester : 9. HTTP Error Response
    else Get Account Succeeded
        AccountService --> AccountService : 7. account
        AccountService -> AccountFirestore : 8. Update(account with Status="blocked")
        activate AccountFirestore
        AccountFirestore --> AccountService : 9. nil / Error
        deactivate AccountFirestore
        alt Update Account Failed
            AccountService --> AccountPutHandler : 10. Error
            AccountPutHandler --> Requester : 11. HTTP Error Response
        else Update Account Succeeded
            AccountService --> AccountPutHandler : 10. nil
            AccountPutHandler --> Requester : 11. HTTP 200 OK (Account Blocked)
        end
    end
    deactivate AccountService
end
deactivate AccountPutHandler
deactivate Requester

@enduml