@startuml
title Account UnBlock - PUT /accounts/:account_id

actor Requester
boundary AccountPutHandler <<accountHandler.go>>
control AccountService <<serviceAccount.go>>
entity AccountFirestore <<model/account/firestore.go>>

activate Requester
Requester -> AccountPutHandler : 1. PUT /accounts/:account_id

activate AccountPutHandler

alt Authorization Failed
    AccountPutHandler --> Requester : 2. HTTP Error Response
else Authorization Succeeded
   
    AccountPutHandler -> AccountService : 2. Update(accountID)
    activate AccountService
    AccountService -> AccountService : 3. Account(accountID)
    AccountService -> AccountFirestore : 4. Get(&accountID)
    activate AccountFirestore
    AccountFirestore --> AccountService : 5. accountData / Error
    deactivate AccountFirestore
    alt Get Account Failed
        AccountService --> AccountService : 6. Error
        AccountService --> AccountPutHandler : 7. Error
        AccountPutHandler --> Requester : 8. HTTP Error Response
    else Get Account Succeeded
        AccountService --> AccountService : 6. account
        AccountService -> AccountFirestore : 7. Update(account with Status="active")
        activate AccountFirestore
        AccountFirestore --> AccountService : 8. nil / Error
        deactivate AccountFirestore
        alt Update Account Failed
            AccountService --> AccountPutHandler : 9. Error
            AccountPutHandler --> Requester : 10. HTTP Error Response
        else Update Account Succeeded
            AccountService --> AccountPutHandler : 9. nil
            AccountPutHandler --> Requester : 10. HTTP 200 OK (Account Blocked)
        end
        deactivate AccountService
    end
    deactivate AccountPutHandler
end
deactivate Requester

@enduml