@startuml
title User UnBlock - PUT /users/:user_id

actor Requester
boundary UserPutHandler <<userHandler.go>>
control UserService <<serviceUser.go>>
entity UserFirestore <<model/user/firestore.go>>

activate Requester
Requester -> UserPutHandler : 1. PUT /users/:user_id

activate UserPutHandler

alt Authorization Failed
    UserPutHandler --> Requester : 2. HTTP Error Response
else Authorization Succeeded
    UserPutHandler -> UserService : 2. Update(userID)
    activate UserService
    UserService -> UserService : 3. User(userID)
    UserService -> UserFirestore : 4. Get(&userID)
    activate UserFirestore
    UserFirestore --> UserService : 5. UserData / Error
    deactivate UserFirestore
    alt Get User Failed
        UserService --> UserService : 6. Error
        UserService --> UserPutHandler : 7. Error
        UserPutHandler --> Requester : 8. HTTP Error Response
    else Get User Succeeded
        UserService --> UserService : 6. User
        UserService -> UserFirestore : 7. Update(User with Status="active")
        activate UserFirestore
        UserFirestore --> UserService : 8. nil / Error
        deactivate UserFirestore
        alt Update User Failed
            UserService --> UserPutHandler : 9. Error
            UserPutHandler --> Requester : 10. HTTP Error Response
        else Update User Succeeded
            UserService --> UserPutHandler : 9. nil
            UserPutHandler --> Requester : 10. HTTP 200 OK (User Blocked)
        end
        deactivate UserService
    end
    deactivate UserPutHandler
end
deactivate Requester

@enduml