@startuml
title Generate User Report - GET /users/:user_id/report

actor Requester
boundary UserGetReportHandler <<userHandler.go>>
control AuthorizeService <<serviceAuthorize.go>>
control UserService <<serviceUser.go>>
entity UserFirestore <<model/user/firestore.go>>
entity ClientFirestore <<model/client/firestore.go>>

Requester -> UserGetReportHandler : 1. GET /users/report/:user_id
activate UserGetReportHandler

UserGetReportHandler -> AuthorizeService : 2. Authorize(Cookie, userID_from_path)
activate AuthorizeService
AuthorizeService -->> UserGetReportHandler : 3. Claims / Error
deactivate AuthorizeService

alt Authorization Failed
    UserGetReportHandler -->> Requester : 4. HTTP Error Response
else Authorization Succeeded
    UserGetReportHandler -> UserService : 5. Report(userID_from_path)
    activate UserService

    UserService -> UserService : 6. Get(userID)
    activate UserService
    UserService -> UserFirestore : 7. Get(&userID)
    activate UserFirestore
    UserFirestore -->> UserService : 8. userInfo / Error
    deactivate UserFirestore
    deactivate UserService

    alt Get UserInfo Failed
        UserService -->> UserGetReportHandler : 9. Error
        UserGetReportHandler -->> Requester : 10. HTTP Error Response
    else Get UserInfo Succeeded
        UserService -> ClientFirestore : 9. GetFiltered(user_id==userID)
        activate ClientFirestore
        ClientFirestore -->> UserService : 11. filteredClients / Error
        deactivate ClientFirestore
        note right of ClientFirestore : Filters clients by userID

        alt Get Clients Failed
            UserService -->> UserGetReportHandler : 13. Error
            UserGetReportHandler -->> Requester : 14. HTTP Error Response
        else Get Clients Succeeded
            note right of UserService : Assembles UserReport
            UserService -->> UserGetReportHandler : 13. userReport
            UserGetReportHandler -->> Requester : 14. HTTP 200 OK (userReport)
        end
    end
    deactivate UserService
end
deactivate UserGetReportHandler
@enduml