@startuml
title Generate Client Report - GET /clients/:client_id/report

actor Requester
boundary ClientGetReportHandler <<clientHandler.go>>
control AuthorizeService <<serviceAuthorize.go>>
control ClientService <<serviceClient.go>>
entity ClientFirestore <<model/client/firestore.go>>
entity AccountFirestore <<model/account/firestore.go>>

Requester -> ClientGetReportHandler : 1. GET /clients/report/:client_id
activate ClientGetReportHandler

alt Authorization Failed
    ClientGetReportHandler -->> Requester : 2. HTTP Error Response
else Authorization Succeeded
    ClientGetReportHandler -> ClientService : 2. Report(clientID_from_path)
    activate ClientService

    ClientService -> ClientService : 3. Get(clientID)
    activate ClientService
    ClientService -> ClientFirestore : 4. Get(&clientID)
    activate ClientFirestore
    ClientFirestore -->> ClientService : 5. clientInfo / Error
    deactivate ClientFirestore
    deactivate ClientService

    alt Get ClientInfo Failed
        ClientService -->> ClientGetReportHandler : 6. Error
        ClientGetReportHandler -->> Requester : 7. HTTP Error Response
    else Get ClientInfo Succeeded
        ClientService -> AccountFirestore : 6. GetFiltered(client_id==clientID)
        activate AccountFirestore
        AccountFirestore -->> ClientService : 7. filteredAccounts / Error
        deactivate AccountFirestore
        note right of AccountFirestore : Filters accounts by clientID

        alt Get Accounts Failed
            ClientService -->> ClientGetReportHandler : 8. Error
            ClientGetReportHandler -->> Requester : 9. HTTP Error Response
        else Get Accounts Succeeded
            note right of ClientService : Assembles ClientReport
            ClientService -->> ClientGetReportHandler : 8. clientReport
            ClientGetReportHandler -->> Requester : 9. HTTP 200 OK (clientReport)
        end
    end
    deactivate ClientService
end
deactivate ClientGetReportHandler
@enduml